module "postgresql_setup" {
  source                            = "../"
  sql_name                          = var.sql_name
  server_version                    = var.server_version
  resource_group_name               = var.resource_group_name
  resource_group_location           = var.resource_group_location
  ssl_enforcement_enabled           = var.ssl_enforcement_enabled
  public_network_access_enabled     = var.public_network_access_enabled
  storage_mb                        = var.storage_mb
  geo_redundant_backup_enabled      = var.geo_redundant_backup_enabled
  backup_retention_days             = var.backup_retention_days
  sku_name                          = var.sku_name
  administrator_login_password      = var.administrator_login_password
  db_charset                        = var.db_charset
  sql_db_name                       = var.sql_db_name
  db_collation                      = var.db_collation
  auto_grow_enabled                 = var.auto_grow_enabled
  admin_login                       = var.admin_login
  subscription_id                   = var.subscription_id
  client_id                         = var.client_id
  client_secret                     = var.client_secret
  tenant_id                         = var.tenant_id
  vnet_name                         = var.vnet_name
  subnet_name                       = var.subnet_name
  vnet_address_range                = var.vnet_address_range
  subnet_address_range              = var.subnet_address_range
  vnet_exists                       = var.vnet_exists
}